spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/authdb
server:
  port: 8081
jwt:
  secret: am9pbmdpcmxhbmltYWxzaG9lYmxpbmRwbGFudGJlbGxjdXJyZW50YWRkaXRpb253YW4=
  expiration-ms: 3600000